# Generated by Django 2.2 on 2019-04-25 00:26

import assignments.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.CharField(choices=[('ap-sp', 'Apache Spark'), ('yn-mp', 'Yarn/Map Reduce'), ('hb', 'HBase')], default='ap-sp', max_length=10, primary_key=True, serialize=False, verbose_name='Environment')),
                ('bash_file_url', models.FilePathField(path='E:\\Sem_8\\Major_Project\\ASP\\assignments/media\\bash_files')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Assignment ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignment Title')),
                ('desc', models.CharField(blank=True, default='No Description', max_length=1000, verbose_name='Assignment Description')),
                ('submission_time', models.DateTimeField(auto_now=True, verbose_name='Time of Submission')),
                ('assign_code', models.FileField(help_text='Upload .zip Files Only', upload_to=assignments.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'], message="Only '.zip' files are allowed!!")])),
                ('run_command', models.CharField(help_text='Enter the command for running your project', max_length=500, verbose_name='Run Command')),
                ('is_eval', models.BooleanField(default=False, verbose_name='Is Evaluated')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Environment', verbose_name='Environment Selected')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
