# Generated by Django 2.2 on 2019-04-25 08:37

import assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20190425_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_code',
            field=models.FileField(blank=True, help_text='Upload .zip Files Only', upload_to=assignments.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'], message="Only '.zip' files are allowed!!")]),
        ),
    ]
