# Generated by Django 2.2 on 2019-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20190425_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Assignment ID'),
        ),
    ]
