# Generated by Django 2.2 on 2019-04-25 16:58

import assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20190425_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_requirements',
            field=models.FileField(help_text='File which contains all the Alpine-Package requirements', upload_to=assignments.models.user_req_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'], message="Only '.txt' files are allowed!!")]),
        ),
    ]
