# Generated by Django 2.2 on 2019-04-25 17:02

import assignments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20190425_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_code',
            field=models.FileField(help_text='Upload .zip Files Only', upload_to=assignments.models.user_code_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'], message="Only '.zip' files are allowed!!")], verbose_name='Code of Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign_requirements',
            field=models.FileField(help_text='File which contains all the Alpine-Package requirements', upload_to=assignments.models.user_req_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'], message="Only '.txt' files are allowed!!")], verbose_name='Requirements of Assignment'),
        ),
    ]
