# Generated by Django 2.2 on 2019-04-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_auto_20190426_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VM',
        ),
    ]
