# Generated by Django 2.2 on 2019-04-26 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190425_0556'),
        ('assignments', '0011_delete_vm'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('port_used', models.IntegerField(verbose_name='Port Used')),
            ],
        ),
    ]
