# Generated by Django 2.2 on 2019-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_vm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='env_id',
            field=models.CharField(choices=[('ap_sp', 'Apache Spark'), ('ap_hp', 'Apache Hadoop')], default='ap-sp', max_length=10, primary_key=True, serialize=False, verbose_name='Environment'),
        ),
    ]
